### ISSUE TITLE
failure as a company

### ISSUE THREAD

**Issue by NoahGeorge7** [chriseklopp/TarkovInventoryAssistant#21] opened 2022-11-13 05:58 UTC
I raised my concurs in previous issue report ticket #3 and I have just been made aware that some nepotistic dev went ahead and closed it without first going through the proper troubleshooting steps. This behavior is unacceptable. I don't know how this company is expected to function with people of such a subpar standard at the helm, failing to take into account legitimate concerns. I don't see any way that this product can be brought to market under such an incompetent team, and frankly I hope they fail before others attempt to use this program and waste their time and effort on this bug filled mess of a product. This product owner has no morals. I was a product tester on 3 separate releases of this, and received no compensation for my tireless work. I will be reporting these actions to the Better Business Bureau, as well as filing a lawsuit for pain and suffering.

fuc u

**Comment by chriseklopp** [comment] 2022-11-13 06:00
LOL


Could not reproduce. Closing

**Closed by chriseklopp** 2022-11-13 06:00 UTC
